// Code generated by goctl. DO NOT EDIT.
package types

type UserRegisterRequest struct {
	Name     string `json:"name"`     // 用户名
	Password string `json:"password"` // 密码
	Email    string `json:"email""`   // 邮箱
	Code     string `json:"code"`     // 验证码
}

type UserRegisterResponse struct {
	Msg  string `json:"msg"`
	Code int    `json:"code"`
}

type LoginRequest struct {
	Name     string `json:"name"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token        string `json:"token"`
	RefreshToken string `json:"refresh_token"`
	Msg          string `json:"msg"`
	Code         int    `json:"code"`
}

type UserDetailRequest struct {
}

type UserDetailResponse struct {
	Name      string `json:"name"`
	Email     string `json:"Email"`
	Avatar    string `json:"avatar"`
	Msg       string `json:"msg"`
	Identity  string `json:"identity"`
	Capacity  int    `json:"capacity"`
	Code      int    `json:"code"`
	CreatedAt string `json:"created_at"`
}
